-- +goose Up
CREATE TABLE indoor_climas (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
	project UUID REFERENCES projects ON DELETE CASCADE UNIQUE NOT NULL,

	attic_zone1_area NUMERIC,
	attic_zone1_u_value NUMERIC,
	attic_zone1_outdoor_temp_n NUMERIC,
	attic_zone1_outdoor_temp_n1 NUMERIC,
	attic_zone1_outdoor_temp_n2 NUMERIC,
	attic_zone1_temp_diff_n NUMERIC,
	attic_zone1_temp_diff_n1 NUMERIC,
	attic_zone1_temp_diff_n2 NUMERIC,
	attic_zone1_heat_loss_coeff NUMERIC,

	attic_zone2_area NUMERIC,
	attic_zone2_u_value NUMERIC,
	attic_zone2_outdoor_temp_n NUMERIC,
	attic_zone2_outdoor_temp_n1 NUMERIC,
	attic_zone2_outdoor_temp_n2 NUMERIC,
	attic_zone2_temp_diff_n NUMERIC,
	attic_zone2_temp_diff_n1 NUMERIC,
	attic_zone2_temp_diff_n2 NUMERIC,
	attic_zone2_heat_loss_coeff NUMERIC,

	basement_ceiling_zone1_area NUMERIC,
	basement_ceiling_zone1_u_value NUMERIC,
	basement_ceiling_zone1_outdoor_temp_n NUMERIC,
	basement_ceiling_zone1_outdoor_temp_n1 NUMERIC,
	basement_ceiling_zone1_outdoor_temp_n2 NUMERIC,
	basement_ceiling_zone1_temp_diff_n NUMERIC,
	basement_ceiling_zone1_temp_diff_n1 NUMERIC,
	basement_ceiling_zone1_temp_diff_n2 NUMERIC,
	basement_ceiling_zone1_heat_loss_coeff NUMERIC,

	basement_ceiling_zone2_area NUMERIC,
	basement_ceiling_zone2_u_value NUMERIC,
	basement_ceiling_zone2_outdoor_temp_n NUMERIC,
	basement_ceiling_zone2_outdoor_temp_n1 NUMERIC,
	basement_ceiling_zone2_outdoor_temp_n2 NUMERIC,
	basement_ceiling_zone2_temp_diff_n NUMERIC,
	basement_ceiling_zone2_temp_diff_n1 NUMERIC,
	basement_ceiling_zone2_temp_diff_n2 NUMERIC,
	basement_ceiling_zone2_heat_loss_coeff NUMERIC,

	external_door_num1_zone1_area NUMERIC,
	external_door_num1_zone1_u_value NUMERIC,
	external_door_num1_zone1_outdoor_temp_n NUMERIC,
	external_door_num1_zone1_outdoor_temp_n1 NUMERIC,
	external_door_num1_zone1_outdoor_temp_n2 NUMERIC,
	external_door_num1_zone1_temp_diff_n NUMERIC,
	external_door_num1_zone1_temp_diff_n1 NUMERIC,
	external_door_num1_zone1_temp_diff_n2 NUMERIC,
	external_door_num1_zone1_heat_loss_coeff NUMERIC,

	external_door_num1_zone2_area NUMERIC,
	external_door_num1_zone2_u_value NUMERIC,
	external_door_num1_zone2_outdoor_temp_n NUMERIC,
	external_door_num1_zone2_outdoor_temp_n1 NUMERIC,
	external_door_num1_zone2_outdoor_temp_n2 NUMERIC,
	external_door_num1_zone2_temp_diff_n NUMERIC,
	external_door_num1_zone2_temp_diff_n1 NUMERIC,
	external_door_num1_zone2_temp_diff_n2 NUMERIC,
	external_door_num1_zone2_heat_loss_coeff NUMERIC,

	external_door_num2_zone1_area NUMERIC,
	external_door_num2_zone1_u_value NUMERIC,
	external_door_num2_zone1_outdoor_temp_n NUMERIC,
	external_door_num2_zone1_outdoor_temp_n1 NUMERIC,
	external_door_num2_zone1_outdoor_temp_n2 NUMERIC,
	external_door_num2_zone1_temp_diff_n NUMERIC,
	external_door_num2_zone1_temp_diff_n1 NUMERIC,
	external_door_num2_zone1_temp_diff_n2 NUMERIC,
	external_door_num2_zone1_heat_loss_coeff NUMERIC,

	external_door_num2_zone2_area NUMERIC,
	external_door_num2_zone2_u_value NUMERIC,
	external_door_num2_zone2_outdoor_temp_n NUMERIC,
	external_door_num2_zone2_outdoor_temp_n1 NUMERIC,
	external_door_num2_zone2_outdoor_temp_n2 NUMERIC,
	external_door_num2_zone2_temp_diff_n NUMERIC,
	external_door_num2_zone2_temp_diff_n1 NUMERIC,
	external_door_num2_zone2_temp_diff_n2 NUMERIC,
	external_door_num2_zone2_heat_loss_coeff NUMERIC,

	external_wall_num1_zone1_area NUMERIC,
	external_wall_num1_zone1_u_value NUMERIC,
	external_wall_num1_zone1_outdoor_temp_n NUMERIC,
	external_wall_num1_zone1_outdoor_temp_n1 NUMERIC,
	external_wall_num1_zone1_outdoor_temp_n2 NUMERIC,
	external_wall_num1_zone1_temp_diff_n NUMERIC,
	external_wall_num1_zone1_temp_diff_n1 NUMERIC,
	external_wall_num1_zone1_temp_diff_n2 NUMERIC,
	external_wall_num1_zone1_heat_loss_coeff NUMERIC,
	external_wall_num1_zone2_area NUMERIC,
	external_wall_num1_zone2_u_value NUMERIC,
	external_wall_num1_zone2_outdoor_temp_n NUMERIC,
	external_wall_num1_zone2_outdoor_temp_n1 NUMERIC,
	external_wall_num1_zone2_outdoor_temp_n2 NUMERIC,
	external_wall_num1_zone2_temp_diff_n NUMERIC,
	external_wall_num1_zone2_temp_diff_n1 NUMERIC,
	external_wall_num1_zone2_temp_diff_n2 NUMERIC,
	external_wall_num1_zone2_heat_loss_coeff NUMERIC,

	external_wall_num2_zone1_area NUMERIC,
	external_wall_num2_zone1_u_value NUMERIC,
	external_wall_num2_zone1_outdoor_temp_n NUMERIC,
	external_wall_num2_zone1_outdoor_temp_n1 NUMERIC,
	external_wall_num2_zone1_outdoor_temp_n2 NUMERIC,
	external_wall_num2_zone1_temp_diff_n NUMERIC,
	external_wall_num2_zone1_temp_diff_n1 NUMERIC,
	external_wall_num2_zone1_temp_diff_n2 NUMERIC,
	external_wall_num2_zone1_heat_loss_coeff NUMERIC,
	external_wall_num2_zone2_area NUMERIC,
	external_wall_num2_zone2_u_value NUMERIC,
	external_wall_num2_zone2_outdoor_temp_n NUMERIC,
	external_wall_num2_zone2_outdoor_temp_n1 NUMERIC,
	external_wall_num2_zone2_outdoor_temp_n2 NUMERIC,
	external_wall_num2_zone2_temp_diff_n NUMERIC,
	external_wall_num2_zone2_temp_diff_n1 NUMERIC,
	external_wall_num2_zone2_temp_diff_n2 NUMERIC,
	external_wall_num2_zone2_heat_loss_coeff NUMERIC,

	external_wall_num3_zone1_area NUMERIC,
	external_wall_num3_zone1_u_value NUMERIC,
	external_wall_num3_zone1_outdoor_temp_n NUMERIC,
	external_wall_num3_zone1_outdoor_temp_n1 NUMERIC,
	external_wall_num3_zone1_outdoor_temp_n2 NUMERIC,
	external_wall_num3_zone1_temp_diff_n NUMERIC,
	external_wall_num3_zone1_temp_diff_n1 NUMERIC,
	external_wall_num3_zone1_temp_diff_n2 NUMERIC,
	external_wall_num3_zone1_heat_loss_coeff NUMERIC,
	external_wall_num3_zone2_area NUMERIC,
	external_wall_num3_zone2_u_value NUMERIC,
	external_wall_num3_zone2_outdoor_temp_n NUMERIC,
	external_wall_num3_zone2_outdoor_temp_n1 NUMERIC,
	external_wall_num3_zone2_outdoor_temp_n2 NUMERIC,
	external_wall_num3_zone2_temp_diff_n NUMERIC,
	external_wall_num3_zone2_temp_diff_n1 NUMERIC,
	external_wall_num3_zone2_temp_diff_n2 NUMERIC,
	external_wall_num3_zone2_heat_loss_coeff NUMERIC,

	external_wall_num4_zone1_area NUMERIC,
	external_wall_num4_zone1_u_value NUMERIC,
	external_wall_num4_zone1_outdoor_temp_n NUMERIC,
	external_wall_num4_zone1_outdoor_temp_n1 NUMERIC,
	external_wall_num4_zone1_outdoor_temp_n2 NUMERIC,
	external_wall_num4_zone1_temp_diff_n NUMERIC,
	external_wall_num4_zone1_temp_diff_n1 NUMERIC,
	external_wall_num4_zone1_temp_diff_n2 NUMERIC,
	external_wall_num4_zone1_heat_loss_coeff NUMERIC,
	external_wall_num4_zone2_area NUMERIC,
	external_wall_num4_zone2_u_value NUMERIC,
	external_wall_num4_zone2_outdoor_temp_n NUMERIC,
	external_wall_num4_zone2_outdoor_temp_n1 NUMERIC,
	external_wall_num4_zone2_outdoor_temp_n2 NUMERIC,
	external_wall_num4_zone2_temp_diff_n NUMERIC,
	external_wall_num4_zone2_temp_diff_n1 NUMERIC,
	external_wall_num4_zone2_temp_diff_n2 NUMERIC,
	external_wall_num4_zone2_heat_loss_coeff NUMERIC,

	window_num1_zone1_area NUMERIC,
	window_num1_zone1_u_value NUMERIC,
	window_num1_zone1_outdoor_temp_n NUMERIC,
	window_num1_zone1_outdoor_temp_n1 NUMERIC,
	window_num1_zone1_outdoor_temp_n2 NUMERIC,
	window_num1_zone1_temp_diff_n NUMERIC,
	window_num1_zone1_temp_diff_n1 NUMERIC,
	window_num1_zone1_temp_diff_n2 NUMERIC,
	window_num1_zone1_heat_loss_coeff NUMERIC,

	window_num1_zone2_area NUMERIC,
	window_num1_zone2_u_value NUMERIC,
	window_num1_zone2_outdoor_temp_n NUMERIC,
	window_num1_zone2_outdoor_temp_n1 NUMERIC,
	window_num1_zone2_outdoor_temp_n2 NUMERIC,
	window_num1_zone2_temp_diff_n NUMERIC,
	window_num1_zone2_temp_diff_n1 NUMERIC,
	window_num1_zone2_temp_diff_n2 NUMERIC,
	window_num1_zone2_heat_loss_coeff NUMERIC,

	window_num2_zone1_area NUMERIC,
	window_num2_zone1_u_value NUMERIC,
	window_num2_zone1_outdoor_temp_n NUMERIC,
	window_num2_zone1_outdoor_temp_n1 NUMERIC,
	window_num2_zone1_outdoor_temp_n2 NUMERIC,
	window_num2_zone1_temp_diff_n NUMERIC,
	window_num2_zone1_temp_diff_n1 NUMERIC,
	window_num2_zone1_temp_diff_n2 NUMERIC,
	window_num2_zone1_heat_loss_coeff NUMERIC,

	window_num2_zone2_area NUMERIC,
	window_num2_zone2_u_value NUMERIC,
	window_num2_zone2_outdoor_temp_n NUMERIC,
	window_num2_zone2_outdoor_temp_n1 NUMERIC,
	window_num2_zone2_outdoor_temp_n2 NUMERIC,
	window_num2_zone2_temp_diff_n NUMERIC,
	window_num2_zone2_temp_diff_n1 NUMERIC,
	window_num2_zone2_temp_diff_n2 NUMERIC,
	window_num2_zone2_heat_loss_coeff NUMERIC,

	ground_zone1_area NUMERIC,
	ground_zone1_u_value NUMERIC,
	ground_zone1_outdoor_temp_n NUMERIC,
	ground_zone1_outdoor_temp_n1 NUMERIC,
	ground_zone1_outdoor_temp_n2 NUMERIC,
	ground_zone1_temp_diff_n NUMERIC,
	ground_zone1_temp_diff_n1 NUMERIC,
	ground_zone1_temp_diff_n2 NUMERIC,
	ground_zone1_heat_loss_coeff NUMERIC,

	ground_zone2_area NUMERIC,
	ground_zone2_u_value NUMERIC,
	ground_zone2_outdoor_temp_n NUMERIC,
	ground_zone2_outdoor_temp_n1 NUMERIC,
	ground_zone2_outdoor_temp_n2 NUMERIC,
	ground_zone2_temp_diff_n NUMERIC,
	ground_zone2_temp_diff_n1 NUMERIC,
	ground_zone2_temp_diff_n2 NUMERIC,
	ground_zone2_heat_loss_coeff NUMERIC,

	roof_zone1_area NUMERIC,
	roof_zone1_u_value NUMERIC,
	roof_zone1_outdoor_temp_n NUMERIC,
	roof_zone1_outdoor_temp_n1 NUMERIC,
	roof_zone1_outdoor_temp_n2 NUMERIC,
	roof_zone1_temp_diff_n NUMERIC,
	roof_zone1_temp_diff_n1 NUMERIC,
	roof_zone1_temp_diff_n2 NUMERIC,
	roof_zone1_heat_loss_coeff NUMERIC,

	roof_zone2_area NUMERIC,
	roof_zone2_u_value NUMERIC,
	roof_zone2_outdoor_temp_n NUMERIC,
	roof_zone2_outdoor_temp_n1 NUMERIC,
	roof_zone2_outdoor_temp_n2 NUMERIC,
	roof_zone2_temp_diff_n NUMERIC,
	roof_zone2_temp_diff_n1 NUMERIC,
	roof_zone2_temp_diff_n2 NUMERIC,
	roof_zone2_heat_loss_coeff NUMERIC,

	basewall_zone1_area NUMERIC,
	basewall_zone1_u_value NUMERIC,
	basewall_zone1_outdoor_temp_n NUMERIC,
	basewall_zone1_outdoor_temp_n1 NUMERIC,
	basewall_zone1_outdoor_temp_n2 NUMERIC,
	basewall_zone1_temp_diff_n NUMERIC,
	basewall_zone1_temp_diff_n1 NUMERIC,
	basewall_zone1_temp_diff_n2 NUMERIC,
	basewall_zone1_heat_loss_coeff NUMERIC,

	basewall_zone2_area NUMERIC,
	basewall_zone2_u_value NUMERIC,
	basewall_zone2_outdoor_temp_n NUMERIC,
	basewall_zone2_outdoor_temp_n1 NUMERIC,
	basewall_zone2_outdoor_temp_n2 NUMERIC,
	basewall_zone2_temp_diff_n NUMERIC,
	basewall_zone2_temp_diff_n1 NUMERIC,
	basewall_zone2_temp_diff_n2 NUMERIC,
	basewall_zone2_heat_loss_coeff NUMERIC,

	total_ht_zone1 NUMERIC,
	total_ht_zone2 NUMERIC,

	total_ht NUMERIC,

	heat_gains_internal NUMERIC,

	heat_gains_solar NUMERIC,

	airex_windows_n NUMERIC,
	airex_windows_n1 NUMERIC,
	airex_windows_n2 NUMERIC,

	airex_building_n NUMERIC,
	airex_building_n1 NUMERIC,
	airex_building_n2 NUMERIC,

	airex_total_n NUMERIC,
	airex_total_n1 NUMERIC,
	airex_total_n2 NUMERIC,

	heated_volume_building NUMERIC,

	total_energy_consumption_n NUMERIC,
	total_energy_consumption_n1 NUMERIC,
	total_energy_consumption_n2 NUMERIC,

	total_e_consumption_circlosses_n NUMERIC,
	total_e_consumption_circlosses_n1 NUMERIC,
	total_e_consumption_circlosses_n2 NUMERIC,

	circulation_losses_n NUMERIC,
	circulation_losses_n1 NUMERIC,
	circulation_losses_n2 NUMERIC,

	distribution_losses_basement NUMERIC,
	distribution_losses_attic NUMERIC,

	total_measured_n NUMERIC,
	total_measured_n1 NUMERIC,
	total_measured_n2 NUMERIC,

	total_calculated_n NUMERIC,
	total_calculated_n1 NUMERIC,
	total_calculated_n2 NUMERIC,

	indoor_temp_n NUMERIC,
	indoor_temp_n1 NUMERIC,
	indoor_temp_n2 NUMERIC,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE pipes (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
	indoorclima UUID REFERENCES indoor_climas ON DELETE CASCADE NOT NULL,

	quality INTEGER,
	installed_length NUMERIC,
	diameter NUMERIC,
	heat_loss_unit NUMERIC,
	heat_loss_year NUMERIC
);

-- +goose Down
DROP TABLE pipes;
DROP TABLE indoor_climas;
