-- +goose Up
CREATE TYPE zone_type AS ENUM (
	'attic_zone1',
	'attic_zone2',
	'basement_ceiling_zone1',
	'basement_ceiling_zone2',
	'ground_zone1',
	'ground_zone2',
	'roof_zone1',
	'roof_zone2',
	'basewall_zone1',
	'basewall_zone2',
	'external_door_env1_zone1',
	'external_door_env1_zone2',
	'external_door_env2_zone1',
	'external_door_env2_zone2',
	'window_env1_zone1',
	'window_env1_zone2',
	'window_env2_zone1',
	'window_env2_zone2',
	'external_wall_env1_zone1',
	'external_wall_env1_zone2',
	'external_wall_env2_zone1',
	'external_wall_env2_zone2',
	'external_wall_env3_zone1',
	'external_wall_env3_zone2',
	'external_wall_env4_zone1',
	'external_wall_env4_zone2'
);

CREATE TABLE ic_zones (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
	indoorclima_id UUID REFERENCES indoor_climas ON DELETE CASCADE NOT NULL,

	type zone_type NOT NULL,
	area NUMERIC DEFAULT 0,
	uvalue NUMERIC DEFAULT 0,
	outdoor_temp_n NUMERIC DEFAULT 0,
	outdoor_temp_n1 NUMERIC DEFAULT 0,
	outdoor_temp_n2 NUMERIC DEFAULT 0,
	temp_diff_n NUMERIC DEFAULT 0,
	temp_diff_n1 NUMERIC DEFAULT 0,
	temp_diff_n2 NUMERIC DEFAULT 0,
	heat_loss_coeff NUMERIC DEFAULT 0,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE,

	UNIQUE (indoorclima_id, type)
);

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION migrate_zones_up() RETURNS VOID AS $$
DECLARE v indoor_climas%rowtype;
DECLARE zone_type TEXT;
DECLARE ic_column TEXT;
BEGIN
	FOR v IN SELECT * FROM indoor_climas LOOP
		FOR zone_type IN SELECT unnest(enum_range(NULL::zone_type)) LOOP
			ic_column := REPLACE(zone_type, '_env', '_num');
			EXECUTE format('INSERT INTO ic_zones (
					indoorclima_id, type, area, uvalue,
					outdoor_temp_n, outdoor_temp_n1, outdoor_temp_n2,
					temp_diff_n, temp_diff_n1, temp_diff_n2,
					heat_loss_coeff
				) VALUES (
					%s, %s, $1.%I, $1.%I,
					$1.%I, $1.%I, $1.%I,
					$1.%I, $1.%I, $1.%I,
					$1.%I)',
				quote_literal(v.id), quote_literal(zone_type), concat(ic_column, '_area'), concat(ic_column, '_u_value'),
				concat(ic_column, '_outdoor_temp_n'), concat(ic_column, '_outdoor_temp_n1'), concat(ic_column, '_outdoor_temp_n2'),
				concat(ic_column, '_temp_diff_n'), concat(ic_column, '_temp_diff_n1'), concat(ic_column, '_temp_diff_n2'),
				concat(ic_column, '_heat_loss_coeff')
			) USING v;
		END LOOP;
	END LOOP;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

SELECT migrate_zones_up();
DROP FUNCTION migrate_zones_up;

ALTER TABLE indoor_climas
	DROP COLUMN attic_zone1_area,
	DROP COLUMN attic_zone1_u_value,
	DROP COLUMN attic_zone1_outdoor_temp_n,
	DROP COLUMN attic_zone1_outdoor_temp_n1,
	DROP COLUMN attic_zone1_outdoor_temp_n2,
	DROP COLUMN attic_zone1_temp_diff_n,
	DROP COLUMN attic_zone1_temp_diff_n1,
	DROP COLUMN attic_zone1_temp_diff_n2,
	DROP COLUMN attic_zone1_heat_loss_coeff,
	DROP COLUMN attic_zone2_area,
	DROP COLUMN attic_zone2_u_value,
	DROP COLUMN attic_zone2_outdoor_temp_n,
	DROP COLUMN attic_zone2_outdoor_temp_n1,
	DROP COLUMN attic_zone2_outdoor_temp_n2,
	DROP COLUMN attic_zone2_temp_diff_n,
	DROP COLUMN attic_zone2_temp_diff_n1,
	DROP COLUMN attic_zone2_temp_diff_n2,
	DROP COLUMN attic_zone2_heat_loss_coeff,
	DROP COLUMN basement_ceiling_zone1_area,
	DROP COLUMN basement_ceiling_zone1_u_value,
	DROP COLUMN basement_ceiling_zone1_outdoor_temp_n,
	DROP COLUMN basement_ceiling_zone1_outdoor_temp_n1,
	DROP COLUMN basement_ceiling_zone1_outdoor_temp_n2,
	DROP COLUMN basement_ceiling_zone1_temp_diff_n,
	DROP COLUMN basement_ceiling_zone1_temp_diff_n1,
	DROP COLUMN basement_ceiling_zone1_temp_diff_n2,
	DROP COLUMN basement_ceiling_zone1_heat_loss_coeff,
	DROP COLUMN basement_ceiling_zone2_area,
	DROP COLUMN basement_ceiling_zone2_u_value,
	DROP COLUMN basement_ceiling_zone2_outdoor_temp_n,
	DROP COLUMN basement_ceiling_zone2_outdoor_temp_n1,
	DROP COLUMN basement_ceiling_zone2_outdoor_temp_n2,
	DROP COLUMN basement_ceiling_zone2_temp_diff_n,
	DROP COLUMN basement_ceiling_zone2_temp_diff_n1,
	DROP COLUMN basement_ceiling_zone2_temp_diff_n2,
	DROP COLUMN basement_ceiling_zone2_heat_loss_coeff,
	DROP COLUMN external_door_num1_zone1_area,
	DROP COLUMN external_door_num1_zone1_u_value,
	DROP COLUMN external_door_num1_zone1_outdoor_temp_n,
	DROP COLUMN external_door_num1_zone1_outdoor_temp_n1,
	DROP COLUMN external_door_num1_zone1_outdoor_temp_n2,
	DROP COLUMN external_door_num1_zone1_temp_diff_n,
	DROP COLUMN external_door_num1_zone1_temp_diff_n1,
	DROP COLUMN external_door_num1_zone1_temp_diff_n2,
	DROP COLUMN external_door_num1_zone1_heat_loss_coeff,
	DROP COLUMN external_door_num1_zone2_area,
	DROP COLUMN external_door_num1_zone2_u_value,
	DROP COLUMN external_door_num1_zone2_outdoor_temp_n,
	DROP COLUMN external_door_num1_zone2_outdoor_temp_n1,
	DROP COLUMN external_door_num1_zone2_outdoor_temp_n2,
	DROP COLUMN external_door_num1_zone2_temp_diff_n,
	DROP COLUMN external_door_num1_zone2_temp_diff_n1,
	DROP COLUMN external_door_num1_zone2_temp_diff_n2,
	DROP COLUMN external_door_num1_zone2_heat_loss_coeff,
	DROP COLUMN external_door_num2_zone1_area,
	DROP COLUMN external_door_num2_zone1_u_value,
	DROP COLUMN external_door_num2_zone1_outdoor_temp_n,
	DROP COLUMN external_door_num2_zone1_outdoor_temp_n1,
	DROP COLUMN external_door_num2_zone1_outdoor_temp_n2,
	DROP COLUMN external_door_num2_zone1_temp_diff_n,
	DROP COLUMN external_door_num2_zone1_temp_diff_n1,
	DROP COLUMN external_door_num2_zone1_temp_diff_n2,
	DROP COLUMN external_door_num2_zone1_heat_loss_coeff,
	DROP COLUMN external_door_num2_zone2_area,
	DROP COLUMN external_door_num2_zone2_u_value,
	DROP COLUMN external_door_num2_zone2_outdoor_temp_n,
	DROP COLUMN external_door_num2_zone2_outdoor_temp_n1,
	DROP COLUMN external_door_num2_zone2_outdoor_temp_n2,
	DROP COLUMN external_door_num2_zone2_temp_diff_n,
	DROP COLUMN external_door_num2_zone2_temp_diff_n1,
	DROP COLUMN external_door_num2_zone2_temp_diff_n2,
	DROP COLUMN external_door_num2_zone2_heat_loss_coeff,
	DROP COLUMN external_wall_num1_zone1_area,
	DROP COLUMN external_wall_num1_zone1_u_value,
	DROP COLUMN external_wall_num1_zone1_outdoor_temp_n,
	DROP COLUMN external_wall_num1_zone1_outdoor_temp_n1,
	DROP COLUMN external_wall_num1_zone1_outdoor_temp_n2,
	DROP COLUMN external_wall_num1_zone1_temp_diff_n,
	DROP COLUMN external_wall_num1_zone1_temp_diff_n1,
	DROP COLUMN external_wall_num1_zone1_temp_diff_n2,
	DROP COLUMN external_wall_num1_zone1_heat_loss_coeff,
	DROP COLUMN external_wall_num1_zone2_area,
	DROP COLUMN external_wall_num1_zone2_u_value,
	DROP COLUMN external_wall_num1_zone2_outdoor_temp_n,
	DROP COLUMN external_wall_num1_zone2_outdoor_temp_n1,
	DROP COLUMN external_wall_num1_zone2_outdoor_temp_n2,
	DROP COLUMN external_wall_num1_zone2_temp_diff_n,
	DROP COLUMN external_wall_num1_zone2_temp_diff_n1,
	DROP COLUMN external_wall_num1_zone2_temp_diff_n2,
	DROP COLUMN external_wall_num1_zone2_heat_loss_coeff,
	DROP COLUMN external_wall_num2_zone1_area,
	DROP COLUMN external_wall_num2_zone1_u_value,
	DROP COLUMN external_wall_num2_zone1_outdoor_temp_n,
	DROP COLUMN external_wall_num2_zone1_outdoor_temp_n1,
	DROP COLUMN external_wall_num2_zone1_outdoor_temp_n2,
	DROP COLUMN external_wall_num2_zone1_temp_diff_n,
	DROP COLUMN external_wall_num2_zone1_temp_diff_n1,
	DROP COLUMN external_wall_num2_zone1_temp_diff_n2,
	DROP COLUMN external_wall_num2_zone1_heat_loss_coeff,
	DROP COLUMN external_wall_num2_zone2_area,
	DROP COLUMN external_wall_num2_zone2_u_value,
	DROP COLUMN external_wall_num2_zone2_outdoor_temp_n,
	DROP COLUMN external_wall_num2_zone2_outdoor_temp_n1,
	DROP COLUMN external_wall_num2_zone2_outdoor_temp_n2,
	DROP COLUMN external_wall_num2_zone2_temp_diff_n,
	DROP COLUMN external_wall_num2_zone2_temp_diff_n1,
	DROP COLUMN external_wall_num2_zone2_temp_diff_n2,
	DROP COLUMN external_wall_num2_zone2_heat_loss_coeff,
	DROP COLUMN external_wall_num3_zone1_area,
	DROP COLUMN external_wall_num3_zone1_u_value,
	DROP COLUMN external_wall_num3_zone1_outdoor_temp_n,
	DROP COLUMN external_wall_num3_zone1_outdoor_temp_n1,
	DROP COLUMN external_wall_num3_zone1_outdoor_temp_n2,
	DROP COLUMN external_wall_num3_zone1_temp_diff_n,
	DROP COLUMN external_wall_num3_zone1_temp_diff_n1,
	DROP COLUMN external_wall_num3_zone1_temp_diff_n2,
	DROP COLUMN external_wall_num3_zone1_heat_loss_coeff,
	DROP COLUMN external_wall_num3_zone2_area,
	DROP COLUMN external_wall_num3_zone2_u_value,
	DROP COLUMN external_wall_num3_zone2_outdoor_temp_n,
	DROP COLUMN external_wall_num3_zone2_outdoor_temp_n1,
	DROP COLUMN external_wall_num3_zone2_outdoor_temp_n2,
	DROP COLUMN external_wall_num3_zone2_temp_diff_n,
	DROP COLUMN external_wall_num3_zone2_temp_diff_n1,
	DROP COLUMN external_wall_num3_zone2_temp_diff_n2,
	DROP COLUMN external_wall_num3_zone2_heat_loss_coeff,
	DROP COLUMN external_wall_num4_zone1_area,
	DROP COLUMN external_wall_num4_zone1_u_value,
	DROP COLUMN external_wall_num4_zone1_outdoor_temp_n,
	DROP COLUMN external_wall_num4_zone1_outdoor_temp_n1,
	DROP COLUMN external_wall_num4_zone1_outdoor_temp_n2,
	DROP COLUMN external_wall_num4_zone1_temp_diff_n,
	DROP COLUMN external_wall_num4_zone1_temp_diff_n1,
	DROP COLUMN external_wall_num4_zone1_temp_diff_n2,
	DROP COLUMN external_wall_num4_zone1_heat_loss_coeff,
	DROP COLUMN external_wall_num4_zone2_area,
	DROP COLUMN external_wall_num4_zone2_u_value,
	DROP COLUMN external_wall_num4_zone2_outdoor_temp_n,
	DROP COLUMN external_wall_num4_zone2_outdoor_temp_n1,
	DROP COLUMN external_wall_num4_zone2_outdoor_temp_n2,
	DROP COLUMN external_wall_num4_zone2_temp_diff_n,
	DROP COLUMN external_wall_num4_zone2_temp_diff_n1,
	DROP COLUMN external_wall_num4_zone2_temp_diff_n2,
	DROP COLUMN external_wall_num4_zone2_heat_loss_coeff,
	DROP COLUMN window_num1_zone1_area,
	DROP COLUMN window_num1_zone1_u_value,
	DROP COLUMN window_num1_zone1_outdoor_temp_n,
	DROP COLUMN window_num1_zone1_outdoor_temp_n1,
	DROP COLUMN window_num1_zone1_outdoor_temp_n2,
	DROP COLUMN window_num1_zone1_temp_diff_n,
	DROP COLUMN window_num1_zone1_temp_diff_n1,
	DROP COLUMN window_num1_zone1_temp_diff_n2,
	DROP COLUMN window_num1_zone1_heat_loss_coeff,
	DROP COLUMN window_num1_zone2_area,
	DROP COLUMN window_num1_zone2_u_value,
	DROP COLUMN window_num1_zone2_outdoor_temp_n,
	DROP COLUMN window_num1_zone2_outdoor_temp_n1,
	DROP COLUMN window_num1_zone2_outdoor_temp_n2,
	DROP COLUMN window_num1_zone2_temp_diff_n,
	DROP COLUMN window_num1_zone2_temp_diff_n1,
	DROP COLUMN window_num1_zone2_temp_diff_n2,
	DROP COLUMN window_num1_zone2_heat_loss_coeff,
	DROP COLUMN window_num2_zone1_area,
	DROP COLUMN window_num2_zone1_u_value,
	DROP COLUMN window_num2_zone1_outdoor_temp_n,
	DROP COLUMN window_num2_zone1_outdoor_temp_n1,
	DROP COLUMN window_num2_zone1_outdoor_temp_n2,
	DROP COLUMN window_num2_zone1_temp_diff_n,
	DROP COLUMN window_num2_zone1_temp_diff_n1,
	DROP COLUMN window_num2_zone1_temp_diff_n2,
	DROP COLUMN window_num2_zone1_heat_loss_coeff,
	DROP COLUMN window_num2_zone2_area,
	DROP COLUMN window_num2_zone2_u_value,
	DROP COLUMN window_num2_zone2_outdoor_temp_n,
	DROP COLUMN window_num2_zone2_outdoor_temp_n1,
	DROP COLUMN window_num2_zone2_outdoor_temp_n2,
	DROP COLUMN window_num2_zone2_temp_diff_n,
	DROP COLUMN window_num2_zone2_temp_diff_n1,
	DROP COLUMN window_num2_zone2_temp_diff_n2,
	DROP COLUMN window_num2_zone2_heat_loss_coeff,
	DROP COLUMN ground_zone1_area,
	DROP COLUMN ground_zone1_u_value,
	DROP COLUMN ground_zone1_outdoor_temp_n,
	DROP COLUMN ground_zone1_outdoor_temp_n1,
	DROP COLUMN ground_zone1_outdoor_temp_n2,
	DROP COLUMN ground_zone1_temp_diff_n,
	DROP COLUMN ground_zone1_temp_diff_n1,
	DROP COLUMN ground_zone1_temp_diff_n2,
	DROP COLUMN ground_zone1_heat_loss_coeff,
	DROP COLUMN ground_zone2_area,
	DROP COLUMN ground_zone2_u_value,
	DROP COLUMN ground_zone2_outdoor_temp_n,
	DROP COLUMN ground_zone2_outdoor_temp_n1,
	DROP COLUMN ground_zone2_outdoor_temp_n2,
	DROP COLUMN ground_zone2_temp_diff_n,
	DROP COLUMN ground_zone2_temp_diff_n1,
	DROP COLUMN ground_zone2_temp_diff_n2,
	DROP COLUMN ground_zone2_heat_loss_coeff,
	DROP COLUMN roof_zone1_area,
	DROP COLUMN roof_zone1_u_value,
	DROP COLUMN roof_zone1_outdoor_temp_n,
	DROP COLUMN roof_zone1_outdoor_temp_n1,
	DROP COLUMN roof_zone1_outdoor_temp_n2,
	DROP COLUMN roof_zone1_temp_diff_n,
	DROP COLUMN roof_zone1_temp_diff_n1,
	DROP COLUMN roof_zone1_temp_diff_n2,
	DROP COLUMN roof_zone1_heat_loss_coeff,
	DROP COLUMN roof_zone2_area,
	DROP COLUMN roof_zone2_u_value,
	DROP COLUMN roof_zone2_outdoor_temp_n,
	DROP COLUMN roof_zone2_outdoor_temp_n1,
	DROP COLUMN roof_zone2_outdoor_temp_n2,
	DROP COLUMN roof_zone2_temp_diff_n,
	DROP COLUMN roof_zone2_temp_diff_n1,
	DROP COLUMN roof_zone2_temp_diff_n2,
	DROP COLUMN roof_zone2_heat_loss_coeff,
	DROP COLUMN basewall_zone1_area,
	DROP COLUMN basewall_zone1_u_value,
	DROP COLUMN basewall_zone1_outdoor_temp_n,
	DROP COLUMN basewall_zone1_outdoor_temp_n1,
	DROP COLUMN basewall_zone1_outdoor_temp_n2,
	DROP COLUMN basewall_zone1_temp_diff_n,
	DROP COLUMN basewall_zone1_temp_diff_n1,
	DROP COLUMN basewall_zone1_temp_diff_n2,
	DROP COLUMN basewall_zone1_heat_loss_coeff,
	DROP COLUMN basewall_zone2_area,
	DROP COLUMN basewall_zone2_u_value,
	DROP COLUMN basewall_zone2_outdoor_temp_n,
	DROP COLUMN basewall_zone2_outdoor_temp_n1,
	DROP COLUMN basewall_zone2_outdoor_temp_n2,
	DROP COLUMN basewall_zone2_temp_diff_n,
	DROP COLUMN basewall_zone2_temp_diff_n1,
	DROP COLUMN basewall_zone2_temp_diff_n2,
	DROP COLUMN basewall_zone2_heat_loss_coeff;

-- +goose Down
ALTER TABLE indoor_climas
	ADD COLUMN attic_zone1_area NUMERIC,
	ADD COLUMN attic_zone1_u_value NUMERIC,
	ADD COLUMN attic_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN attic_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN attic_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN attic_zone1_temp_diff_n NUMERIC,
	ADD COLUMN attic_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN attic_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN attic_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN attic_zone2_area NUMERIC,
	ADD COLUMN attic_zone2_u_value NUMERIC,
	ADD COLUMN attic_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN attic_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN attic_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN attic_zone2_temp_diff_n NUMERIC,
	ADD COLUMN attic_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN attic_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN attic_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN basement_ceiling_zone1_area NUMERIC,
	ADD COLUMN basement_ceiling_zone1_u_value NUMERIC,
	ADD COLUMN basement_ceiling_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN basement_ceiling_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN basement_ceiling_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN basement_ceiling_zone1_temp_diff_n NUMERIC,
	ADD COLUMN basement_ceiling_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN basement_ceiling_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN basement_ceiling_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN basement_ceiling_zone2_area NUMERIC,
	ADD COLUMN basement_ceiling_zone2_u_value NUMERIC,
	ADD COLUMN basement_ceiling_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN basement_ceiling_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN basement_ceiling_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN basement_ceiling_zone2_temp_diff_n NUMERIC,
	ADD COLUMN basement_ceiling_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN basement_ceiling_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN basement_ceiling_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_door_num1_zone1_area NUMERIC,
	ADD COLUMN external_door_num1_zone1_u_value NUMERIC,
	ADD COLUMN external_door_num1_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_door_num1_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_door_num1_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_door_num1_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_door_num1_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_door_num1_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_door_num1_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_door_num1_zone2_area NUMERIC,
	ADD COLUMN external_door_num1_zone2_u_value NUMERIC,
	ADD COLUMN external_door_num1_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_door_num1_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_door_num1_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_door_num1_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_door_num1_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_door_num1_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_door_num1_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_door_num2_zone1_area NUMERIC,
	ADD COLUMN external_door_num2_zone1_u_value NUMERIC,
	ADD COLUMN external_door_num2_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_door_num2_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_door_num2_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_door_num2_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_door_num2_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_door_num2_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_door_num2_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_door_num2_zone2_area NUMERIC,
	ADD COLUMN external_door_num2_zone2_u_value NUMERIC,
	ADD COLUMN external_door_num2_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_door_num2_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_door_num2_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_door_num2_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_door_num2_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_door_num2_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_door_num2_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num1_zone1_area NUMERIC,
	ADD COLUMN external_wall_num1_zone1_u_value NUMERIC,
	ADD COLUMN external_wall_num1_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num1_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num1_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num1_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num1_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num1_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num1_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num1_zone2_area NUMERIC,
	ADD COLUMN external_wall_num1_zone2_u_value NUMERIC,
	ADD COLUMN external_wall_num1_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num1_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num1_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num1_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num1_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num1_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num1_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num2_zone1_area NUMERIC,
	ADD COLUMN external_wall_num2_zone1_u_value NUMERIC,
	ADD COLUMN external_wall_num2_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num2_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num2_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num2_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num2_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num2_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num2_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num2_zone2_area NUMERIC,
	ADD COLUMN external_wall_num2_zone2_u_value NUMERIC,
	ADD COLUMN external_wall_num2_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num2_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num2_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num2_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num2_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num2_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num2_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num3_zone1_area NUMERIC,
	ADD COLUMN external_wall_num3_zone1_u_value NUMERIC,
	ADD COLUMN external_wall_num3_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num3_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num3_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num3_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num3_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num3_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num3_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num3_zone2_area NUMERIC,
	ADD COLUMN external_wall_num3_zone2_u_value NUMERIC,
	ADD COLUMN external_wall_num3_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num3_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num3_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num3_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num3_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num3_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num3_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num4_zone1_area NUMERIC,
	ADD COLUMN external_wall_num4_zone1_u_value NUMERIC,
	ADD COLUMN external_wall_num4_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num4_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num4_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num4_zone1_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num4_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num4_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num4_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN external_wall_num4_zone2_area NUMERIC,
	ADD COLUMN external_wall_num4_zone2_u_value NUMERIC,
	ADD COLUMN external_wall_num4_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN external_wall_num4_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN external_wall_num4_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN external_wall_num4_zone2_temp_diff_n NUMERIC,
	ADD COLUMN external_wall_num4_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN external_wall_num4_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN external_wall_num4_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN window_num1_zone1_area NUMERIC,
	ADD COLUMN window_num1_zone1_u_value NUMERIC,
	ADD COLUMN window_num1_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN window_num1_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN window_num1_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN window_num1_zone1_temp_diff_n NUMERIC,
	ADD COLUMN window_num1_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN window_num1_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN window_num1_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN window_num1_zone2_area NUMERIC,
	ADD COLUMN window_num1_zone2_u_value NUMERIC,
	ADD COLUMN window_num1_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN window_num1_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN window_num1_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN window_num1_zone2_temp_diff_n NUMERIC,
	ADD COLUMN window_num1_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN window_num1_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN window_num1_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN window_num2_zone1_area NUMERIC,
	ADD COLUMN window_num2_zone1_u_value NUMERIC,
	ADD COLUMN window_num2_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN window_num2_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN window_num2_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN window_num2_zone1_temp_diff_n NUMERIC,
	ADD COLUMN window_num2_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN window_num2_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN window_num2_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN window_num2_zone2_area NUMERIC,
	ADD COLUMN window_num2_zone2_u_value NUMERIC,
	ADD COLUMN window_num2_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN window_num2_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN window_num2_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN window_num2_zone2_temp_diff_n NUMERIC,
	ADD COLUMN window_num2_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN window_num2_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN window_num2_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN ground_zone1_area NUMERIC,
	ADD COLUMN ground_zone1_u_value NUMERIC,
	ADD COLUMN ground_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN ground_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN ground_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN ground_zone1_temp_diff_n NUMERIC,
	ADD COLUMN ground_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN ground_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN ground_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN ground_zone2_area NUMERIC,
	ADD COLUMN ground_zone2_u_value NUMERIC,
	ADD COLUMN ground_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN ground_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN ground_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN ground_zone2_temp_diff_n NUMERIC,
	ADD COLUMN ground_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN ground_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN ground_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN roof_zone1_area NUMERIC,
	ADD COLUMN roof_zone1_u_value NUMERIC,
	ADD COLUMN roof_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN roof_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN roof_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN roof_zone1_temp_diff_n NUMERIC,
	ADD COLUMN roof_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN roof_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN roof_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN roof_zone2_area NUMERIC,
	ADD COLUMN roof_zone2_u_value NUMERIC,
	ADD COLUMN roof_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN roof_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN roof_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN roof_zone2_temp_diff_n NUMERIC,
	ADD COLUMN roof_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN roof_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN roof_zone2_heat_loss_coeff NUMERIC,
	ADD COLUMN basewall_zone1_area NUMERIC,
	ADD COLUMN basewall_zone1_u_value NUMERIC,
	ADD COLUMN basewall_zone1_outdoor_temp_n NUMERIC,
	ADD COLUMN basewall_zone1_outdoor_temp_n1 NUMERIC,
	ADD COLUMN basewall_zone1_outdoor_temp_n2 NUMERIC,
	ADD COLUMN basewall_zone1_temp_diff_n NUMERIC,
	ADD COLUMN basewall_zone1_temp_diff_n1 NUMERIC,
	ADD COLUMN basewall_zone1_temp_diff_n2 NUMERIC,
	ADD COLUMN basewall_zone1_heat_loss_coeff NUMERIC,
	ADD COLUMN basewall_zone2_area NUMERIC,
	ADD COLUMN basewall_zone2_u_value NUMERIC,
	ADD COLUMN basewall_zone2_outdoor_temp_n NUMERIC,
	ADD COLUMN basewall_zone2_outdoor_temp_n1 NUMERIC,
	ADD COLUMN basewall_zone2_outdoor_temp_n2 NUMERIC,
	ADD COLUMN basewall_zone2_temp_diff_n NUMERIC,
	ADD COLUMN basewall_zone2_temp_diff_n1 NUMERIC,
	ADD COLUMN basewall_zone2_temp_diff_n2 NUMERIC,
	ADD COLUMN basewall_zone2_heat_loss_coeff NUMERIC;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION migrate_zones_down() RETURNS VOID AS $$
DECLARE v indoor_climas%rowtype;
DECLARE z ic_zones%rowtype;
DECLARE ic_column TEXT;
BEGIN
	FOR v IN SELECT * FROM indoor_climas LOOP
		FOR z IN (SELECT * FROM ic_zones WHERE indoorclima_id = v.id) LOOP
			ic_column := REPLACE(z.type::TEXT, '_env', '_num');
			EXECUTE 'UPDATE indoor_climas SET ' ||
				format('%I_area = %s, ', quote_ident(ic_column), z.area) ||
				format('%I_u_value = %s, ', quote_ident(ic_column), z.uvalue) ||
				format('%I_outdoor_temp_n = %s, ', quote_ident(ic_column), z.outdoor_temp_n) ||
				format('%I_outdoor_temp_n1 = %s, ', quote_ident(ic_column), z.outdoor_temp_n1) ||
				format('%I_outdoor_temp_n2 = %s, ', quote_ident(ic_column), z.outdoor_temp_n2) ||
				format('%I_temp_diff_n = %s, ', quote_ident(ic_column), z.temp_diff_n) ||
				format('%I_temp_diff_n1 = %s, ', quote_ident(ic_column), z.temp_diff_n1) ||
				format('%I_temp_diff_n2 = %s, ', quote_ident(ic_column), z.temp_diff_n2) ||
				format('%I_heat_loss_coeff = %s ', quote_ident(ic_column), z.heat_loss_coeff) ||
				format('WHERE id = %s', quote_literal(v.id));
		END LOOP;
	END LOOP;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

SELECT migrate_zones_down();
DROP FUNCTION migrate_zones_down;

DROP TABLE ic_zones;
DROP TYPE zone_type;
