-- +goose Up
UPDATE contracts SET tables = tables || '{"baseconditions_n":{"rows": [["January", "", "", "", ""], ["February", "", "", "", ""], ["March", "", "", "", ""], ["April", "", "", "", ""], ["May", "", "", "", ""], ["June", "", "", "", ""], ["July", "", "", "", ""], ["August", "", "", "", ""], ["September", "", "", "", ""], ["October", "", "", "", ""], ["November", "", "", "", ""], ["December", "", "", "", ""]], "columns": [{"kind": 1, "name": "", "headers": ["Symbol", "Unit"]}, {"kind": 5, "name": "Heating days", "headers": ["Dapk", "Days"]}, {"kind": 4, "name": "Outdoor temperature", "headers": ["T1", "°C"]}, {"kind": 4, "name": "Average indoor temperature", "headers": ["T3", "°C"]}, {"kind": 4, "name": "Degree Days", "headers": ["GDD", "-"]}]}}';

UPDATE contracts SET tables = tables || '{"baseconditions_n_1":{"rows": [["January", "", "", "", ""], ["February", "", "", "", ""], ["March", "", "", "", ""], ["April", "", "", "", ""], ["May", "", "", "", ""], ["June", "", "", "", ""], ["July", "", "", "", ""], ["August", "", "", "", ""], ["September", "", "", "", ""], ["October", "", "", "", ""], ["November", "", "", "", ""], ["December", "", "", "", ""]], "columns": [{"kind": 1, "name": "", "headers": ["Symbol", "Unit"]}, {"kind": 5, "name": "Heating days", "headers": ["Dapk", "Days"]}, {"kind": 4, "name": "Outdoor temperature", "headers": ["T1", "°C"]}, {"kind": 4, "name": "Average indoor temperature", "headers": ["T3", "°C"]}, {"kind": 4, "name": "Degree Days", "headers": ["GDD", "-"]}]}}';

UPDATE contracts SET tables = tables || '{"baseconditions_n_2":{"rows": [["January", "", "", "", ""], ["February", "", "", "", ""], ["March", "", "", "", ""], ["April", "", "", "", ""], ["May", "", "", "", ""], ["June", "", "", "", ""], ["July", "", "", "", ""], ["August", "", "", "", ""], ["September", "", "", "", ""], ["October", "", "", "", ""], ["November", "", "", "", ""], ["December", "", "", "", ""]], "columns": [{"kind": 1, "name": "", "headers": ["Symbol", "Unit"]}, {"kind": 5, "name": "Heating days", "headers": ["Dapk", "Days"]}, {"kind": 4, "name": "Outdoor temperature", "headers": ["T1", "°C"]}, {"kind": 4, "name": "Average indoor temperature", "headers": ["T3", "°C"]}, {"kind": 4, "name": "Degree Days", "headers": ["GDD", "-"]}]}}';

-- +goose Down
UPDATE contracts set tables = tables - 'baseconditions_n';
UPDATE contracts set tables = tables - 'baseconditions_n_1';
UPDATE contracts set tables = tables - 'baseconditions_n_2';
